version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./services/nginx-templates:/etc/nginx/templates
    ports:
      - 3002:80
    environment:
      GOLLUM_HOST: localgollum.chardskarth.me
      GOLLUM_DOCKER_HOSTNAME: gollum
      GOLLUM_DOCKER_HOSTNAME_WITHPATH: gollumwithpath
      GOLLUM_DOCKER_PORT: 4567
      GENERIC_HOSTNAME: local.chardskarth.me

  gollum:
    image: gollumwiki/gollum:v5.3.2
    volumes:
      - ./services/wiki:/wiki
    command:
      - "--port 4567 --ref main ."
    ports:
      - 3003:4567

  gollumwithpath:
    image: gollumwiki/gollum:v5.3.2
    volumes:
      - ./services/wiki:/wiki
    command:
      - "--port 4567 --ref main --base-path /gollum ."
    ports:
      - 3004:4567

